#!/bin/bash
wlr-randr --output HDMI-A-1 --mode 1366x768 &
riverctl default-layout rivertile &
rivertile -view-padding 0 -outer-padding 0 &
swaybg -i $HOME/.wallpaper/pixelwp.png -m fill &
dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river &

riverctl map normal Super Z spawn alacritty
riverctl map normal Super R spawn kickoff
riverctl map normal Super C close
riverctl map normal Super F toggle-float
riverctl map normal Super+Shift Q exit
riverctl keyboard-layout -options "grp:win_space_toggle" "us,ru"

for i in $(seq 1 9); do
	riverctl map normal Super $i set-focused-tags $((1 << ($i - 1)));
done
